name: Nightly Release

on:
  push:
    branches:
      - 'main'

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}
      change_log: ${{ steps.changelog.outputs.clean_changelog }}
      version: ${{ steps.changelog.outputs.version }}
      tag: ${{ steps.changelog.outputs.tag }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get Commit Hash
        run: echo "COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Get Package Version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      # - name: Conventional Changelog Action
      #   id: changelog
      #   uses: Tormak9970/reliable-changelog@v1
      #   with:
      #     github-token: ${{ secrets.github_token }}
      #     current-version: './package.json'
      #     version-path: 'version'
      #     patch-commit-bump-interval: '10'

      - name: Create Release
        id: create-release
        uses: actions/github-script@v6
        # env:
        # RELEASE_TAG: ${{ steps.changelog.outputs.tag }}
        # RELEASE_LOG: ${{ steps.changelog.outputs.clean_changelog }}
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `nightly-${process.env.COMMIT_HASH}`,
              name: `Clippit Nightly ${process.env.COMMIT_HASH}`,
              body: `idk buh`,
              draft: true,
              prerelease: true
            });

            core.setOutput("tag", `nightly-${process.env.COMMIT_HASH}`);

            return data.id

  build-tauri:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Remove Sidecar Deps (Linux)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sed '/\"externalBin\"/d' ./src-tauri/tauri.conf.json > /tmp/tauri.conf.json
          mv /tmp/tauri.conf.json ./src-tauri/tauri.conf.json

      - name: Download FFMpeg (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          curl -L https://github.com/GyanD/codexffmpeg/releases/download/6.0/ffmpeg-6.0-full_build.zip --output ${{ runner.temp }}\ffmpeg.zip
          tar -xvf ${{ runner.temp }}\ffmpeg.zip -C "${{ runner.temp }}" ffmpeg-6.0-full_build/bin/ffmpeg.exe ffmpeg-6.0-full_build/bin/ffprobe.exe
          mkdir ".\src-tauri\binaries"
          copy "${{ runner.temp }}\ffmpeg-6.0-full_build\bin\ffmpeg.exe" ".\src-tauri\binaries\ffmpeg-x86_64-pc-windows-msvc.exe"
          copy "${{ runner.temp }}\ffmpeg-6.0-full_build\bin\ffprobe.exe" ".\src-tauri\binaries\ffprobe-x86_64-pc-windows-msvc.exe"

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies (Linux Only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build App
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          tagName: ${{ needs.create-release.outputs.tag }}
          releaseBody: 'Download the release for your platform below'
          releaseDraft: true
          includeUpdaterJson: true

  publish-release:
    needs: [create-release, build-tauri]
    permissions:
      contents: write
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Update Release Assets
        uses: ./.github/workflows/create-release-assets
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ needs.create-release.outputs.release_id }}
          release_tag: ${{ needs.create-release.outputs.tag }}
          git_branch: 'main'

      - name: Publish Release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: true
            })
